name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Run lint
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v1

    - name: Install Cocoapods
      run: gem install cocoapods

    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings